# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projekty\Qt\GPilot\src\gpilot\ui\forms\partials\main\partmainconsole.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_partMainConsole(object):
    def setupUi(self, partMainConsole):
        partMainConsole.setObjectName("partMainConsole")
        partMainConsole.resize(483, 483)
        self.gridLayout = QtWidgets.QGridLayout(partMainConsole)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(partMainConsole)
        self.frame.setFrameShape(QtCore.Qt.QFrame::Shape::NoFrame)
        self.frame.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.txtConsole = QtWidgets.QPlainTextEdit(self.frame)
        self.txtConsole.setMinimumSize(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtConsole.setFont(font)
        self.txtConsole.setReadOnly(True)
        self.txtConsole.setObjectName("txtConsole")
        self.verticalLayout_14.addWidget(self.txtConsole)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cboCommand = ComboBox(self.frame)
        self.cboCommand.setStyleSheet("padding-top: 3;\n"
"padding-bottom: 3;\n"
"padding-right: 8;")
        self.cboCommand.setEditable(True)
        self.cboCommand.setMaxVisibleItems(10)
        self.cboCommand.setMaxCount(25)
        self.cboCommand.setInsertPolicy(QtCore.Qt.QComboBox::InsertPolicy::InsertAtTop)
        self.cboCommand.setFrame(True)
        self.cboCommand.setObjectName("cboCommand")
        self.horizontalLayout_7.addWidget(self.cboCommand)
        self.cmdCommandSend = QtWidgets.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/send_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdCommandSend.setIcon(icon)
        self.cmdCommandSend.setIconSize(QtCore.QSize(16, 16))
        self.cmdCommandSend.setObjectName("cmdCommandSend")
        self.horizontalLayout_7.addWidget(self.cmdCommandSend)
        self.cmdClearConsole = QtWidgets.QPushButton(self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/erase_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdClearConsole.setIcon(icon1)
        self.cmdClearConsole.setIconSize(QtCore.QSize(16, 16))
        self.cmdClearConsole.setObjectName("cmdClearConsole")
        self.horizontalLayout_7.addWidget(self.cmdClearConsole)
        self.horizontalLayout_7.setStretch(0, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_7)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(partMainConsole)
        self.cmdCommandSend.clicked.connect(partMainConsole.onSendClicked) # type: ignore
        self.cmdClearConsole.clicked.connect(partMainConsole.onClearClicked) # type: ignore
        self.cboCommand.returnPressed.connect(partMainConsole.onSendClicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(partMainConsole)

    def retranslateUi(self, partMainConsole):
        _translate = QtCore.QCoreApplication.translate
        partMainConsole.setWindowTitle(_translate("partMainConsole", "Form"))
        self.cmdCommandSend.setToolTip(_translate("partMainConsole", "Send command"))
        self.cmdClearConsole.setToolTip(_translate("partMainConsole", "Clear console"))
from ui.widgets.combobox import ComboBox
import images_rc
